-- CIBUSPAN ONE: usuarios, roles, permisos y auditoría.
-- Ejecutar una sola vez en el SQL Editor de Supabase o con Supabase CLI.

create table if not exists public.app_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  nombre text,
  rol text not null default 'BODEGUERO' check (rol in (
    'ADMINISTRADOR', 'GERENTE', 'BODEGUERO',
    'GERENTE_OPERACIONES', 'JEFA_FACTURACION'
  )),
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.app_role_permissions (
  rol text not null check (rol in (
    'ADMINISTRADOR', 'GERENTE', 'BODEGUERO',
    'GERENTE_OPERACIONES', 'JEFA_FACTURACION'
  )),
  pantalla text not null,
  permitido boolean not null default true,
  primary key (rol, pantalla)
);

create table if not exists public.app_user_permissions (
  user_id uuid not null references auth.users(id) on delete cascade,
  pantalla text not null,
  permitido boolean not null,
  actualizado_en timestamptz not null default now(),
  actualizado_por uuid references auth.users(id) on delete set null,
  primary key (user_id, pantalla)
);

create table if not exists public.app_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  accion text not null,
  detalle jsonb,
  creado_en timestamptz not null default now()
);

create or replace function public.app_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  rol_inicial text;
begin
  rol_inicial := case
    when new.raw_user_meta_data ->> 'rol' in (
      'ADMINISTRADOR', 'GERENTE', 'BODEGUERO',
      'GERENTE_OPERACIONES', 'JEFA_FACTURACION'
    ) then new.raw_user_meta_data ->> 'rol'
    else 'BODEGUERO'
  end;

  insert into public.app_profiles (user_id, email, nombre, rol)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'nombre', ''),
    rol_inicial
  )
  on conflict (user_id) do update set
    email = excluded.email,
    nombre = coalesce(excluded.nombre, public.app_profiles.nombre),
    actualizado_en = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_app_profile on auth.users;
create trigger on_auth_user_created_app_profile
after insert or update of email, raw_user_meta_data on auth.users
for each row execute procedure public.app_handle_new_user();

-- Crea perfiles para usuarios que ya existían antes de instalar esta migración.
insert into public.app_profiles (user_id, email, nombre, rol)
select
  u.id,
  coalesce(u.email, ''),
  nullif(u.raw_user_meta_data ->> 'nombre', ''),
  case
    when u.raw_user_meta_data ->> 'rol' in (
      'ADMINISTRADOR', 'GERENTE', 'BODEGUERO',
      'GERENTE_OPERACIONES', 'JEFA_FACTURACION'
    ) then u.raw_user_meta_data ->> 'rol'
    else 'BODEGUERO'
  end
from auth.users u
on conflict (user_id) do update set email = excluded.email;

-- El usuario más antiguo queda como administrador inicial si todavía no existe uno.
update public.app_profiles
set rol = 'ADMINISTRADOR', actualizado_en = now()
where user_id = (
  select u.id from auth.users u order by u.created_at asc limit 1
)
and not exists (
  select 1 from public.app_profiles where rol = 'ADMINISTRADOR'
);

delete from public.app_role_permissions;

with pantallas(pantalla) as (
  values
    ('Dashboard'), ('Pedidos'), ('Inventario'), ('Producción'),
    ('Semielaborados'), ('Despachos'), ('Historial despachos'),
    ('Devoluciones'), ('Reportes'), ('Documentos'),
    ('Hoja de producción'), ('Hoja de despacho'), ('Anexo Supermaxi'),
    ('Administración'), ('Materias primas'), ('Preformulación'),
    ('Usuarios y permisos')
)
insert into public.app_role_permissions (rol, pantalla, permitido)
select 'ADMINISTRADOR', pantalla, true from pantallas
union all
select 'GERENTE', pantalla, true
from pantallas where pantalla <> 'Usuarios y permisos';

insert into public.app_role_permissions (rol, pantalla, permitido) values
  ('BODEGUERO', 'Despachos', true),
  ('GERENTE_OPERACIONES', 'Pedidos', true),
  ('GERENTE_OPERACIONES', 'Inventario', true),
  ('GERENTE_OPERACIONES', 'Despachos', true),
  ('GERENTE_OPERACIONES', 'Devoluciones', true),
  ('GERENTE_OPERACIONES', 'Documentos', true),
  ('JEFA_FACTURACION', 'Reportes', true),
  ('JEFA_FACTURACION', 'Documentos', true);

create or replace function public.app_es_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.app_profiles p
    where p.user_id = p_user_id
      and p.activo
      and p.rol = 'ADMINISTRADOR'
  );
$$;

create or replace function public.app_puede(
  p_pantalla text,
  p_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when p_pantalla = 'Usuarios y permisos' then public.app_es_admin(p_user_id)
    else coalesce(
      (
        select up.permitido
        from public.app_user_permissions up
        where up.user_id = p_user_id and up.pantalla = p_pantalla
      ),
      (
        select rp.permitido
        from public.app_profiles p
        join public.app_role_permissions rp on rp.rol = p.rol
        where p.user_id = p_user_id
          and p.activo
          and rp.pantalla = p_pantalla
      ),
      false
    )
  end;
$$;

create or replace function public.app_mis_permisos()
returns table (pantalla text, permitido boolean)
language sql
stable
security definer
set search_path = public
as $$
  with pantallas as (
    select rp.pantalla
    from public.app_profiles p
    join public.app_role_permissions rp on rp.rol = p.rol
    where p.user_id = auth.uid() and p.activo
    union
    select up.pantalla
    from public.app_user_permissions up
    where up.user_id = auth.uid()
  )
  select
    ps.pantalla,
    case
      when ps.pantalla = 'Usuarios y permisos' then public.app_es_admin()
      else coalesce(
        (select up.permitido from public.app_user_permissions up
         where up.user_id = auth.uid() and up.pantalla = ps.pantalla),
        (select rp.permitido
         from public.app_profiles p
         join public.app_role_permissions rp on rp.rol = p.rol
         where p.user_id = auth.uid() and rp.pantalla = ps.pantalla),
        false
      )
    end as permitido
  from pantallas ps
  order by ps.pantalla;
$$;

alter table public.app_profiles enable row level security;
alter table public.app_role_permissions enable row level security;
alter table public.app_user_permissions enable row level security;
alter table public.app_audit_log enable row level security;

drop policy if exists app_profiles_lectura on public.app_profiles;
create policy app_profiles_lectura on public.app_profiles
for select to authenticated
using (user_id = auth.uid() or public.app_es_admin());

drop policy if exists app_profiles_admin_actualiza on public.app_profiles;
create policy app_profiles_admin_actualiza on public.app_profiles
for update to authenticated
using (public.app_es_admin())
with check (public.app_es_admin());

drop policy if exists app_roles_lectura on public.app_role_permissions;
create policy app_roles_lectura on public.app_role_permissions
for select to authenticated using (true);

drop policy if exists app_permisos_lectura on public.app_user_permissions;
create policy app_permisos_lectura on public.app_user_permissions
for select to authenticated
using (user_id = auth.uid() or public.app_es_admin());

drop policy if exists app_permisos_admin on public.app_user_permissions;
create policy app_permisos_admin on public.app_user_permissions
for all to authenticated
using (public.app_es_admin())
with check (public.app_es_admin());

drop policy if exists app_auditoria_admin_lectura on public.app_audit_log;
create policy app_auditoria_admin_lectura on public.app_audit_log
for select to authenticated using (public.app_es_admin());

grant select on public.app_profiles to authenticated;
grant select on public.app_role_permissions to authenticated;
grant select on public.app_user_permissions to authenticated;
grant select on public.app_audit_log to authenticated;
grant execute on function public.app_es_admin(uuid) to authenticated;
grant execute on function public.app_puede(text, uuid) to authenticated;
grant execute on function public.app_mis_permisos() to authenticated;
